import { SessionProvider } from "@/components/SessionProvider";
import NavBar from "@/components/NavBar";
import { getServerSession } from "next-auth";
import "@/styles/globals.css";
import { Session } from "next-auth";
import NextAuth from "@/pages/api/auth/[...nextauth]";
import Login from "@/components/Login";
export const metadata = {
  title: "VayuDhara",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session: Session | null = await getServerSession(NextAuth);
  console.log(session);
  return (
    <html lang="en">
      <body className="max-w-[425px] mx-auto">
        <SessionProvider session={session}>
          {!session ? (
            <Login />
          ) : (
            <>
              <NavBar />
              <div>{children}</div>
            </>
          )}
        </SessionProvider>
      </body>
    </html>
  );
}
